image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

install:
  - java -jar ./artifacts/app-order.jar

build: off

build_script:
  - chmod +x gradlew
  - chmod +x driver/win/chromedriver.exe
  - ./gradlew test --info





